Repository RamenDR/ramen, pull requests merged in 2023-10, with the labels that each got.

#1057 Upgrade to rook 1.12
  test/addons/rook-cluster/start
  test/addons/rook-operator/start
  test/addons/rook-toolbox/start
Labels: test

#1053 VRG: Handle Kube objects recovery point pointer update errors
  controllers/volumereplicationgroup_controller.go
  controllers/vrg_kubeobjects.go
  controllers/vrg_vrgobject.go
Labels: high

#1054 Fix VRG upload tests
  controllers/vrg_volrep_test.go
  controllers/vrg_vrgobject.go
Labels: low
